---
- name: Install coturn
  apt:
    name: coturn
    update_cache: true
    state: present

- name: Copy coturn config-file
  template:
    src: "turnserver.conf.j2"
    dest: /etc/turnserver.conf

- name: Enable logrotate for coturn
  template:
    src: logrotate/coturn
    dest: /etc/logrotate.d/coturn

- name: Enable coturn server in defaults
  lineinfile:
    path: /etc/default/coturn
    regexp: 'TURNSERVER_ENABLED'
    line: 'TURNSERVER_ENABLED=1'
  notify: restart coturn

- name: Enable coturn
  service:
    name: coturn
    enabled: true
    state: started
