---
- name: Install required packages
  apt:
    name:
    - language-pack-en
    - software-properties-common
    - haveged
    - curl
    - python-apt
    - python-dev
    - python3-dev
    - python-wheel
    - python3-wheel
    - openjdk-8-jdk
    update_cache: yes
    state: present

- name: set version of java to use
  file:
    src: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
    dest: /etc/alternatives/java
    state: link
  notify: restart bigbluebutton

- import_tasks: locale.yml

- name: add BigBlueButton apt key
  apt_key:
    url: http://ubuntu.bigbluebutton.org/bigbluebutton.asc
    id: '{{ bbb_apt_key }}'
    state: present

- name: add multiverse apt repositories
  apt_repository: repo={{ item }} state=present
  with_items:
    - 'deb http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial multiverse'
    - 'deb http://archive.ubuntu.com/ubuntu xenial-updates multiverse'
    - 'deb-src http://archive.ubuntu.com/ubuntu xenial-updates multiverse'

- name: add mongodb apt key
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-3.4.asc
    state: present

- name: add bigbluebutton apt key
  apt_key:
    url: https://ubuntu.bigbluebutton.org/repo/bigbluebutton.asc
    state: present

- name: add dependency apt repositories
  apt_repository: repo={{ item }} state=present
  with_items:
    - ppa:bigbluebutton/support
    - ppa:rmescandon/yq
    - deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.4 multiverse
    - deb https://ubuntu.bigbluebutton.org/xenial-220/ bigbluebutton-xenial main

- name: install bbb and dependencies
  apt:
    name:
    - mongodb-org
    - bbb-check
    - bbb-html5
    - bigbluebutton
    state: present

- import_tasks: letsencrypt.yml
  when: bbb_letsencrypt_enable

- import_tasks: config.yml

- import_tasks: coturn.yml
  when: bbb_coturn_enable

- import_tasks: greenlight.yml
  when: bbb_greenlight_enable
